import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import Navbar from './navbar/page'
import Footer from './footer/page'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Start Up Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
         <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
